{
  "AccountId": applicationRecordUid,
  "LastName": lastName,
  "FirstName": firstName,
  "Salutation": salutation,
  "OtherStreet": address.street,
  "OtherCity": address.city,
  "OtherState": address.region,
  "OtherPostalCode": address.zipCode,
  "OtherCountry": "",
  "MailingStreet": "",
  "MailingCity": "",
  "MailingState": "",
  "MailingPostalCode": "",
  "MailingCountry": "",
  "Phone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "primary"}), "value"),
  "Fax": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "fax"}), "value"),
  "MobilePhone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "mobile"}), "value"),
  "HomePhone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "private"}), "value"),
  "OtherPhone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "secondary"}), "value"),
  "AssistantPhone": "",
  "ReportsToId": "",
  "Email": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "email"}), "value"),
  "Title": title,
  "Department": "",
  "AssistantName": "",
  "LeadSource": "",
  "Birthdate": birthday,
  "Description": notes,
  "OwnerId": "",
  "EmailBouncedReason": "",
  "EmailBouncedDate": "",
  "Jigsaw": "",
  "Level__c": "",
  "Languages__c": language,
  "extID__c": ""
}
