{
      "updated_date": $substringBefore(oihApplicationRecords.lastModified, " "),
      "address_category2": " ",
      "phone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "primary"}), "value"),
      "wp_contact_remote_addr": "",
      "phone3": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "tertiary"}), "value"),
      "status_date": "",
      "picture": "",
      "company": "",
      "line_category2": "",
      "address_location_formatted": "",
      "private_email": "",
      "colspan": "",
      "email_check_result": "",
      "address_category1": " ",
      "private_street_number": "",
      "mandant": "",
      "position": "",
      "private_state": address.region,
      "private_country_symbol": address.countryCode,
      "mobile_phone": "",
      "email_save_note": "",
      "updated_by_user": "",
      "rowid": oihApplicationRecords.recordUid,
      "oldstatus_remarks": "",
      "picture_url": photo,
      "deactivated": "",
      "delete_link": "",
      "serial_salutation": "",
      "house_post_code": "",
      "history_log": "",
      "for_table": "",
      "class_name": "",
      "firstname": firstName,
      "standard_person": "",
      "same_contactperson": "",
      "status_time": "",
      "column_header": "",
      "private_email_save_note": "",
      "private_phone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "private"}), "value"),
      "private_street": address.street,
      "updated_time": $substringAfter(oihApplicationRecords.lastModified, " "),
      "detail": "",
      "eternal_exclusion_from_all_mailinglists": "",
      "privphone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "private secondary"}), "value"),
      "status_locked": "",
      "address_category3": "",
      "birthday": birthday,
      "remarks": "",
      "column_output": "",
      "fax": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "fax" and $v.description = "primary"}), "value"),
      "caring_employee": "",
      "last_update": oihApplicationRecords.lastModified,
      "address_category4": "",
      "created_by_wp_contact": "0",
      "salutation": salutation,
      "updated_by_user_group": "",
      "phone2": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "secondary"}), "value"),
      "oldstatus": "",
      "title": title,
      "private_country": address.country,
      "private_mobile_phone": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "phone" and $v.description = "private mobile"}), "value"),
      "private_zip_code": address.zipCode,
      "name": lastName,
      "import_key": "",
      "xing_url": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "xing"}), "value"),
      "url": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "url"}), "value"),
      "email": $lookup($filter(contactData, function($v, $i, $a) { $v.type = "email"}), "value"),
      "line_category1": "",
      "private_town": "",
      "department": "",
      "for_rowid": ""
}
